# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20160510083444) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "local_authorities", force: :cascade do |t|
    t.text "name"
  end

  create_table "local_authority_results", force: :cascade do |t|
    t.integer "local_authority_id"
    t.string  "result_type"
    t.integer "result_year"
    t.integer "total_pupils"
    t.float   "ks2_percent_low_ks1_attainers"
    t.float   "ks2_percent_medium_ks1_attainers"
    t.float   "ks2_percent_high_ks1_attainers"
    t.float   "ks2_percent_disadvantaged"
    t.float   "ks2_percent_not_disadvantaged"
    t.float   "ks2_percent_EAL"
    t.float   "ks2_percent_non_mobile"
    t.float   "ks2_percent_special_needs"
    t.float   "ks2_percent_2_levels_progress_maths"
    t.float   "ks2_percent_boys_2_levels_progress_maths"
    t.float   "ks2_percent_girls_2_levels_progress_maths"
    t.float   "ks2_percent_low_PA_2_levels_progress_maths"
    t.float   "ks2_percent_med_PA_2_levels_progress_maths"
    t.float   "ks2_percent_high_PA_2_levels_progress_maths"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_maths"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_maths"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_maths"
    t.float   "ks2_percent_EAL_2_levels_progress_maths"
    t.float   "ks2_percent_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_2_levels_progress_reading"
    t.float   "ks2_percent_boys_2_levels_progress_reading"
    t.float   "ks2_percent_girls_2_levels_progress_reading"
    t.float   "ks2_percent_low_PA_2_levels_progress_reading"
    t.float   "ks2_percent_med_PA_2_levels_progress_reading"
    t.float   "ks2_percent_high_PA_2_levels_progress_reading"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_reading"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_reading"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_reading"
    t.float   "ks2_percent_EAL_2_levels_progress_reading"
    t.float   "ks2_percent_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_2_levels_progress_writing"
    t.float   "ks2_percent_boys_2_levels_progress_writing"
    t.float   "ks2_percent_girls_2_levels_progress_writing"
    t.float   "ks2_percent_low_PA_2_levels_progress_writing"
    t.float   "ks2_percent_med_PA_2_levels_progress_writing"
    t.float   "ks2_percent_high_PA_2_levels_progress_writing"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_writing"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_writing"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_writing"
    t.float   "ks2_percent_EAL_2_levels_progress_writing"
    t.float   "ks2_percent_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_level_4_above_RWM"
    t.float   "ks2_percent_level_4_above_RWM_2012"
    t.float   "ks2_percent_level_4_above_RWM_2013"
    t.float   "ks2_percent_level_4_above_RWM_2014"
    t.float   "ks2_percent_level_4B_above_RWM"
    t.float   "ks2_percent_level_4B_above_RWM_2013"
    t.float   "ks2_percent_level_4B_above_RWM_2014"
    t.float   "ks2_percent_level_5_above_RWM"
    t.float   "ks2_percent_level_5_above_RWM_2012"
    t.float   "ks2_percent_level_5_above_RWM_2013"
    t.float   "ks2_percent_level_5_above_RWM_2014"
    t.float   "ks2_percent_level_3_below_RWM"
    t.float   "ks2_value_added"
    t.float   "ks2_percent_disadvantaged_2012"
    t.float   "ks2_percent_disadvantaged_2013"
    t.float   "ks2_percent_disadvantaged_2014"
    t.float   "ks2_percent_not_disadvantaged_2012"
    t.float   "ks2_percent_not_disadvantaged_2013"
    t.float   "ks2_percent_not_disadvantaged_2014"
    t.float   "percent_SEN_statement"
  end

  add_index "local_authority_results", ["local_authority_id"], name: "index_local_authority_results_on_local_authority_id", using: :btree

  create_table "school_results", force: :cascade do |t|
    t.integer "school_id"
    t.integer "local_authority_id"
    t.integer "academy_urn"
    t.string  "result_type"
    t.integer "result_year"
    t.integer "total_pupils"
    t.boolean "is_special"
    t.boolean "new_school"
    t.float   "ks2_percent_low_ks1_attainers"
    t.float   "ks2_percent_medium_ks1_attainers"
    t.float   "ks2_percent_high_ks1_attainers"
    t.float   "ks2_percent_disadvantaged"
    t.float   "ks2_percent_not_disadvantaged"
    t.float   "ks2_percent_EAL"
    t.float   "ks2_percent_non_mobile"
    t.float   "ks2_percent_special_needs"
    t.float   "ks2_percent_2_levels_progress_maths"
    t.float   "ks2_percent_boys_2_levels_progress_maths"
    t.float   "ks2_percent_girls_2_levels_progress_maths"
    t.float   "ks2_percent_low_PA_2_levels_progress_maths"
    t.float   "ks2_percent_med_PA_2_levels_progress_maths"
    t.float   "ks2_percent_high_PA_2_levels_progress_maths"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_maths"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_maths"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_maths"
    t.float   "ks2_percent_EAL_2_levels_progress_maths"
    t.float   "ks2_percent_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_maths_3YR_avg"
    t.float   "ks2_percent_2_levels_progress_reading"
    t.float   "ks2_percent_boys_2_levels_progress_reading"
    t.float   "ks2_percent_girls_2_levels_progress_reading"
    t.float   "ks2_percent_low_PA_2_levels_progress_reading"
    t.float   "ks2_percent_med_PA_2_levels_progress_reading"
    t.float   "ks2_percent_high_PA_2_levels_progress_reading"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_reading"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_reading"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_reading"
    t.float   "ks2_percent_EAL_2_levels_progress_reading"
    t.float   "ks2_percent_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_reading_3YR_avg"
    t.float   "ks2_percent_2_levels_progress_writing"
    t.float   "ks2_percent_boys_2_levels_progress_writing"
    t.float   "ks2_percent_girls_2_levels_progress_writing"
    t.float   "ks2_percent_low_PA_2_levels_progress_writing"
    t.float   "ks2_percent_med_PA_2_levels_progress_writing"
    t.float   "ks2_percent_high_PA_2_levels_progress_writing"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_writing"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_writing"
    t.float   "ks2_percent_GAP_disadvantaged_others_2_levels_progress_writing"
    t.float   "ks2_percent_EAL_2_levels_progress_writing"
    t.float   "ks2_percent_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_disadvantaged_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_not_disadvantaged_2_levels_progress_writing_3YR_avg"
    t.float   "ks2_percent_level_4_above_RWM"
    t.float   "ks2_percent_level_4_above_RWM_2012"
    t.float   "ks2_percent_level_4_above_RWM_2013"
    t.float   "ks2_percent_level_4_above_RWM_2014"
    t.float   "ks2_percent_level_4B_above_RWM"
    t.float   "ks2_percent_level_4B_above_RWM_2013"
    t.float   "ks2_percent_level_4B_above_RWM_2014"
    t.float   "ks2_percent_level_5_above_RWM"
    t.float   "ks2_percent_level_5_above_RWM_2012"
    t.float   "ks2_percent_level_5_above_RWM_2013"
    t.float   "ks2_percent_level_5_above_RWM_2014"
    t.float   "ks2_percent_level_3_below_RWM"
    t.float   "ks2_value_added"
    t.float   "ks2_percent_disadvantaged_2012"
    t.float   "ks2_percent_disadvantaged_2013"
    t.float   "ks2_percent_disadvantaged_2014"
    t.float   "ks2_percent_not_disadvantaged_2012"
    t.float   "ks2_percent_not_disadvantaged_2013"
    t.float   "ks2_percent_not_disadvantaged_2014"
    t.float   "percent_SEN_statement"
  end

  add_index "school_results", ["local_authority_id"], name: "index_school_results_on_local_authority_id", using: :btree
  add_index "school_results", ["school_id"], name: "index_school_results_on_school_id", using: :btree

  create_table "schools", force: :cascade do |t|
    t.integer "local_authority_id"
    t.text    "school_name"
    t.text    "address_street"
    t.text    "address_line_two"
    t.text    "address_line_three"
    t.text    "address_town"
    t.string  "address_postcode"
    t.string  "telephone_number"
    t.boolean "pending_closure"
    t.text    "school_type"
    t.text    "school_sub_type"
    t.boolean "is_primary"
    t.boolean "is_secondary"
    t.boolean "is_post_16"
    t.integer "age_lowest"
    t.integer "age_highest"
    t.text    "gender"
    t.text    "sixth_form_gender"
    t.text    "religious_denomination"
    t.text    "admission_policy"
    t.decimal "lon"
    t.decimal "lat"
    t.boolean "is_closed"
  end

  add_index "schools", ["local_authority_id"], name: "index_schools_on_local_authority_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "name_first"
    t.string   "name_last"
    t.string   "email"
    t.string   "password_digest"
    t.text     "photo"
    t.string   "postcode"
    t.decimal  "lat"
    t.decimal  "lon"
    t.boolean  "admin",           default: false
    t.datetime "created_at",                      null: false
    t.datetime "updated_at",                      null: false
  end

  add_foreign_key "local_authority_results", "local_authorities"
  add_foreign_key "school_results", "local_authorities"
  add_foreign_key "school_results", "schools"
  add_foreign_key "schools", "local_authorities"
end
